compressionLevel: mixed

enableGlobalCache: false

supportedArchitectures:
  cpu:
    - x64
    - current
  libc:
    - current
    - musl
  os:
    - linux
    - current

yarnPath: .yarn/releases/yarn-4.2.2.cjs
